# создание продукта
POST http://localhost:8000/api/v1/products/
Content-Type: application/json

{
  "title": "Лук",
  "description": "ФУУУУУУУУ"
}

###

# получение продуктов
GET http://localhost:8000/api/v1/products/
Content-Type: application/json

###

# обновление продукта
PATCH http://localhost:8000/api/v1/products/3/
Content-Type: application/json

{
  "description": "Самые сочные и ароматные помидорки"
}

###

# удаление продукта
DELETE http://localhost:8000/api/v1/products/1/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET http://localhost:8000/api/v1/products/?search=помид
Content-Type: application/json

###

# поиск продуктов по названию и описанию но с заменой ключевого слова
GET http://localhost:8000/api/v1/products/?q=помид
Content-Type: application/json

###
# сортировка
GET http://localhost:8000/api/v1/products/?ordering=title
Content-Type: application/json

###

# просмотр складов
GET http://localhost:8000/api/v1/stocks/
Content-Type: application/json

###

# просмотр складов но номеру
GET http://localhost:8000/api/v1/stocks/14/
Content-Type: application/json

###

# создание склада
POST http://localhost:8000/api/v1/stocks/
Content-Type: application/json

{
  "address": "лукина варина 3",
  "positions": [
    {
      "product": 4,
      "quantity": 17,
      "price": 1734
    }
  ]
}

###

# создание склада #2 - ПУСТОГО
POST http://localhost:8000/api/v1/stocks/
Content-Type: application/json

{
  "address": "луковый склад"
}

###


# удаление склада по номеру
DELETE http://localhost:8000/api/v1/stocks/12/
Content-Type: application/json

###

# обновляем записи на складе по его номеру
PATCH http://localhost:8000/api/v1/stocks/14/
Content-Type: application/json

{
  "positions": [
    {
      "product": 2,
      "quantity": 0,
      "price": 1300.80
    },
    {
      "product": 3,
      "quantity": 156,
      "price": 1450
    }
  ]
}

###

# обновляем записи на складе по его номеру, 2
PATCH http://localhost:8000/api/v1/stocks/14/
Content-Type: application/json

{
  "positions": [
    {
      "product": 2,
      "quantity": 0,
      "price": 222
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET http://localhost:8000/api/v1/stocks/?products=5
Content-Type: application/json
